# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - app-001-step3-1-suzuyu-node-5

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm' # npmのキャッシュを有効化

      - name: Install dependencies
        run: npm ci # package-lock.json に基づいてクリーンインストール

      - name: Build application
        run: npm run build --if-present
        # ビルド時に環境変数が必要な場合は以下のように env を設定
        # env:
        #   NEXT_PUBLIC_API_ENDPOINT: ${{ secrets.AZURE_FASTAPI_APP_URL }} # 例

      # - name: Run tests (if any)
      #   run: npm run test --if-present

      - name: Create deployment package (excluding node_modules)
        run: |
          mkdir -p deploy_package
          cp -r .next deploy_package/
          if [ -d "public" ]; then cp -r public deploy_package/; else echo "Public directory not found, skipping copy."; fi # publicフォルダが存在する場合のみコピー
          cp package.json deploy_package/
          cp package-lock.json deploy_package/ # 依存関係の解決に必要
          if [ -f next.config.js ]; then cp next.config.js deploy_package/; fi
          # その他、ルートに必要な設定ファイルがあればここに追加
          cd deploy_package
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production' # GitHub Environment名
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip -d extracted_app # 展開先ディレクトリを指定

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-001-step3-1-suzuyu-node-5'
          slot-name: 'Production' # 'Production'スロットを使用しない場合は省略可
          package: extracted_app # 展開したディレクトリを指定
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B1FDC51C3E854874BBDB628FF17BF52F }}
